# Generated by Django 5.2.5 on 2025-11-03 16:42

import api.models
import ckeditor.fields
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Başlyk')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('img', models.ImageField(upload_to=api.models.carousel_upload_path, verbose_name='Surat')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Baglanyşyk')),
                ('is_active', models.BooleanField(default=True, verbose_name='Işjeň')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tertip')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
            ],
            options={
                'verbose_name': 'Karusel suraty',
                'verbose_name_plural': 'Karusel suratlary',
                'ordering': ['order', '-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=8, unique=True)),
                ('checked', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Salgy')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaddresses', to='api.address', verbose_name='Baş salgy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awtor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bahasy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('where', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nire')),
                ('nirden', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nireden')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Soňky sene')),
                ('bring', models.BooleanField(default=False, verbose_name='Getir')),
                ('vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Eni')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzynlygy')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.logist_upload_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
            ],
            options={
                'verbose_name': 'Logistika',
                'verbose_name_plural': 'Logistikalar',
                'ordering': ['-created', 'checked'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageLogist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.multi_image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('logist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.logist', verbose_name='Haryt')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.logistcategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Logistika kategoriýasy',
                'verbose_name_plural': 'Logistika kategoriýalar',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='logist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logistcategory', verbose_name='Kategoriýa'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awtor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bahasy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.service_upload_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
            ],
            options={
                'verbose_name': 'Hyzmat',
                'verbose_name_plural': 'Hyzmatlar',
                'ordering': ['-created', 'checked'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.multi_image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.service', verbose_name='Haryt')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.servicecategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Hyzmat kategoriýasy',
                'verbose_name_plural': 'Hyzmat kategoriýalar',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecategory', verbose_name='Kategoriýa'),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awtor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bahasy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.sparepart_upload_path)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zapçast belgisi')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ýyl')),
                ('condition', models.CharField(choices=[('new', 'Täze'), ('used', 'Ulanylan'), ('refurbished', 'Dikelden')], default='used', max_length=20, verbose_name='Ýagdaýy')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
            ],
            options={
                'ordering': ['-created', 'checked'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.multi_image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.sparepart', verbose_name='Ätiýaçlyk şaý')),
            ],
            options={
                'verbose_name': 'Ätiýaçlyk şaý suraty',
                'verbose_name_plural': 'Ätiýaçlyk şaý suratlary',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.sparepartcategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Ätiýaçlyk şaý kategoriýasy',
                'verbose_name_plural': 'Ätiýaçlyk şaý kategoriýalar',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sparepartcategory', verbose_name='Kategoriýa'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awtor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bahasy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Eni')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzynlygy')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.vehicle_upload_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
                ('current_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_vehicles', to='api.address', verbose_name='Häzirki salgy')),
            ],
            options={
                'verbose_name': 'Ulag',
                'verbose_name_plural': 'Ulaglar',
                'ordering': ['-created', 'checked'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.multi_image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.vehicle', verbose_name='Haryt')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ady')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.vehiclecategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Ulag kategoriýasy',
                'verbose_name_plural': 'Ulag kategoriýalar',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiclecategory', verbose_name='Kategoriýa'),
        ),
    ]
