# Generated by Django 4.2.9 on 2025-05-28 07:56

import api.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Salgy')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subaddresses', to='api.address', verbose_name='Baş salgy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_car)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Awotulag',
                'verbose_name_plural': 'Awtoulaglar',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ady')),
                ('img', models.ImageField(null=True, upload_to='carousel', verbose_name='Surat')),
            ],
            options={
                'verbose_name': 'Banner surat',
                'verbose_name_plural': 'Banner suratlar',
            },
        ),
        migrations.CreateModel(
            name='Elin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_elin)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
            ],
            options={
                'verbose_name': 'Elin',
                'verbose_name_plural': 'Elin',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Habar kategoriýasy')),
            ],
            options={
                'verbose_name': 'Habar kategoriýasy',
                'verbose_name_plural': 'Habar kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, null=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
            ],
            options={
                'verbose_name': 'Ulanyjy',
                'verbose_name_plural': 'Ulanyjylar',
            },
        ),
        migrations.CreateModel(
            name='TopProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Ady')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Kategoriýa')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Awtor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Bahasy')),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('phone', models.IntegerField(null=True, verbose_name='Telefon belgisi')),
                ('img', models.ImageField(null=True, upload_to='top_product/', verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
            ],
            options={
                'verbose_name': 'Saýlanan',
                'verbose_name_plural': 'Saýlananlar',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.servicecategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Hyzmatlar kategoriýasy',
                'verbose_name_plural': 'Hyzmatlar kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_hyzmat)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicecategory')),
            ],
            options={
                'verbose_name': 'Hyzmatlar',
                'verbose_name_plural': 'Hyzmatlar',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='OtherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.othercategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Beýleki kategoriýasy',
                'verbose_name_plural': 'Beýleki kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_beyleki)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.othercategory')),
            ],
            options={
                'verbose_name': 'Beylekiler',
                'verbose_name_plural': 'Beylekiler',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Ady')),
                ('author', models.CharField(max_length=150, null=True, verbose_name='Awtor')),
                ('img', models.ImageField(null=True, upload_to='habarlar/', verbose_name='Surat')),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.newscategory', verbose_name='Kategoriýa')),
            ],
            options={
                'verbose_name': 'Habar',
                'verbose_name_plural': 'Habarlar',
                'ordering': ['-created', 'checked'],
            },
        ),
        migrations.CreateModel(
            name='LogistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.logistcategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Logist kategoriýasy',
                'verbose_name_plural': 'Logist kategoriýalar',
            },
        ),
        migrations.CreateModel(
            name='Logist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('where', models.CharField(max_length=20, null=True)),
                ('nirden', models.CharField(max_length=20, null=True)),
                ('last_date', models.DateField(null=True)),
                ('bring', models.BooleanField(default=False)),
                ('vip', models.BooleanField(default=False)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_logist)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Eni')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzynlygy')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logistcategory')),
            ],
            options={
                'verbose_name': 'Logistika',
                'verbose_name_plural': 'Logistikalar',
                'ordering': ['checked', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.TopProducts.image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('top', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.topproducts', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Saýlanan surat',
                'verbose_name_plural': 'Saýlanan suratlar',
            },
        ),
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_hyzmat, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.service', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Hyzmat surat',
                'verbose_name_plural': 'Hyzmat suratlar',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ImageOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.images_add_beyleki, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('other', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.other', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Beyleki surat',
                'verbose_name_plural': 'Beyleki suratlar',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ImageLogist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.images_add_logist, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('logist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.logist', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Logistika surat',
                'verbose_name_plural': 'Logistika suratlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageElin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.images_add_elin, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('elin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.elin', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Elin surat',
                'verbose_name_plural': 'Elin suratlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.images_add_car, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.car', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Awtoulag surat',
                'verbose_name_plural': 'Awtoulag suratlar',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ElinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.elincategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Elin kategoriýasy',
                'verbose_name_plural': 'Elin kategoriýalar',
            },
        ),
        migrations.AddField(
            model_name='elin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elincategory'),
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.carcategory', verbose_name='Baş kategoriýa')),
            ],
            options={
                'verbose_name': 'Awtoulag kategoriýasy',
                'verbose_name_plural': 'Awtoulag kategoriýalar',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carcategory'),
        ),
    ]
