# Generated by Django 5.2.5 on 2025-11-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='title',
        ),
    ]
