# Generated by Django 4.2.9 on 2025-05-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_topproducts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salgy'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='elin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='elincategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logistcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Habar kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='other',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='othercategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topproducts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ady'),
        ),
    ]
