# Generated by Django 5.2.5 on 2025-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carouselimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady'),
        ),
    ]
