# Generated by Django 4.2.9 on 2025-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_name_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprod',
            name='checked_sms',
            field=models.BooleanField(default=False),
        ),
    ]
