# Generated by Django 5.2.5 on 2025-12-10 04:18

import api.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carouselimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ady')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awtor')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Giňişleýin')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bahasy')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Döredilen wagty')),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategoriya')),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.top_product_upload_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address', verbose_name='Salgy')),
            ],
            options={
                'verbose_name': 'Top Haryt',
                'verbose_name_plural': 'Top Harytlar',
                'ordering': ['-created', 'checked'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.multi_image_upload_path, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('top_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.topproduct', verbose_name='Suratlar')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
