# Generated by Django 4.2.9 on 2025-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprod_checked_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprod',
            name='checked_sms',
        ),
        migrations.AddField(
            model_name='userprod',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
