# Generated by Django 5.2.5 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topproduct_imagetopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='logist',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Musderi'),
        ),
        migrations.AddField(
            model_name='userprod',
            name='phone_model',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='logist',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Ini'),
        ),
    ]
