# Generated by Django 5.2.5 on 2026-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_logist_is_client_userprod_phone_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logist',
            options={'ordering': ['checked', '-created'], 'verbose_name': 'Logistika', 'verbose_name_plural': 'Logistikalar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['checked', '-created'], 'verbose_name': 'Hyzmat', 'verbose_name_plural': 'Hyzmatlar'},
        ),
        migrations.AlterModelOptions(
            name='sparepart',
            options={'ordering': ['checked', '-created']},
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'ordering': ['checked', '-created'], 'verbose_name': 'Top Haryt', 'verbose_name_plural': 'Top Harytlar'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['checked', '-created'], 'verbose_name': 'Ulag', 'verbose_name_plural': 'Ulaglar'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(default=True, max_length=100, verbose_name='Markasy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=True, max_length=50, verbose_name='Reňki'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Goşmaça maglumat'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(decimal_places=1, default=True, max_digits=3, verbose_name='Motor göwrümi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('electric', 'Elektrik'), ('hybrid', 'Gibrid')], default=True, max_length=20, verbose_name='Ýangyç görnüşi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Mehanika'), ('automatic', 'Awtomat')], default=True, max_length=20, verbose_name='Geçiriji guty (Korobka)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=True, verbose_name='Ýörelen ýoly (km)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=True, max_length=100, verbose_name='Modeli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='VIN kody'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=True, verbose_name='Ýyly'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=12, verbose_name='Bahasy'),
            preserve_default=False,
        ),
    ]
