# Generated by Django 4.2.9 on 2025-05-30 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprod_checked_sms_userprod_sms_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprod',
            name='sms_sent_at',
        ),
    ]
