# Generated by Django 4.2.9 on 2025-06-11 15:41

import api.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_userprod_sms_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogistCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=8, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('img', models.ImageField(null=True, upload_to=api.models.image_add_logist)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checked', models.BooleanField(default=False, verbose_name='Barlandy')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Eni')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Uzynlygy')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.address')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.logistcategory')),
                ('current_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_address', to='api.address')),
            ],
            options={
                'verbose_name': 'Logistika ulag',
                'verbose_name_plural': 'Logistika ulaglar',
                'ordering': ['checked', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ImageLogistCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=api.models.images_add_logist, verbose_name='Surat')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Döredilen wagty')),
                ('logist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.logistcar', verbose_name='Haryt')),
            ],
            options={
                'verbose_name': 'Logistika ulag surat',
                'verbose_name_plural': 'Logistika ulag suratlar',
                'ordering': ['-created'],
            },
        ),
    ]
