# Generated by Django 5.2.5 on 2026-01-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_logist_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
    ]
