# Generated by Django 5.2.5 on 2026-02-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_vehicle_brand_remove_vehicle_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='model',
        ),
    ]
