# Generated by Django 5.2.5 on 2026-02-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_sparepart_brand_remove_sparepart_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='compatibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
